### ISSUE TITLE
Just iMHC Scoring Method

### ISSUE THREAD

**Issue by kanefos** [phbradley/conga#27]
Hi authors,

Love CONGA, super interesting innovative idea.

I work with a lot of bulk repertoire seq and would love to start trying to incorporate some of the biology you touched on when you identified the iMHC population. 

Briefly, if I simply take the functions and files in `imhc_scoring.py` and feed these info each other will I acquire a way to score TCRs by their iMHC? Apologies if this is a slightly naive question but if you could lay out how I would go about doing this I would very grateful

Thanks,

**Comment by phbradley** [comment]
Yes, that is definitely do-able. How many TCRs would you want to score, roughly? ANd would these be beta chain sequences? Just curious if we'll need to do any optimization...
