### ISSUE TITLE
Save plots as svg

### ISSUE THREAD

**Issue by CR-94** [phbradley/conga#36]
Hello,

would it be possible to save the graph-vs-graph logos plot as svg instead of png?

Thank you for your help

**Comment by sschattgen** [comment]
Sorry for the delay getting to your issue, and maybe you've found a solution already, but I pushed a commit to the `bcr` developmental branch that should help. Passing `save_pdf = True` to `conga.plotting.make_graph_vs_graph_logos` `conga.plotting.make_tcr_clumping_plots` will write the plots to both png and pdf format. If you really need SVG format you could easily tweak this to get that instead. As a word of caution, you should expect the pdf files to be large file sizes.

Cheers,
Stefan

[https://github.com/phbradley/conga/commit/05674918f37545976ae3ad66e4f55103043b5b8f](url)
