### ISSUE TITLE
Merging Multiple TCR Files

### ISSUE THREAD

**Issue by kkearns13** [phbradley/conga#46]
Hi,

Thank you for developing CoNGA! I have an integrated RDS object and 11 TCR contig files generated from TRUST4 in a 10x format, but I wasn't sure how to compile them into one file so that I could run CoNGA. I looked at issue #28 which referenced a function called `make_10x_clones_file_batch` but I couldn't find this script? I made a .csv file with two columns for the file path and suffix (-1, -2, etc.). I also saw that there is some documentation for merging multiple datasets [https://github.com/phbradley/conga/blob/master/README.md#merging-multiple-datasets-into-a-single-object-for-conga-analysis](url) but am not sure how to amend it to add the suffix to the barcodes etc. Any help would be much appreciated! Thank you!

**Comment by kkearns13** [comment]
Oh never mind! I was looking in the wrong place - I didn't realize it wasn't its own script. For future reference you can import it with:
`from conga.tcrdist.make_10x_clones_file import make_10x_clones_file_batch`

**Comment by phbradley** [comment]
OK, glad you figured it out; and sorry it wasn't more clear to begin with!
Take care,
Phil
________________________________

**Comment by kkearns13** [comment]
No worries! I'm not used to python so it's a bit of a learning curve for me!
