### ISSUE TITLE
Where is the ‘Notes’ in ipynb?

### ISSUE THREAD

**Issue by winglet0996** [phbradley/conga#71]
I am following your [fancy_conga_pipeline_with_batches_and_gammadelta_tcrs](https://nbviewer.org/github/phbradley/conga/blob/master/simple_conga_pipeline.ipynb) tutorial. I noticed in the command cells there are 'Notes' # 1,2,3,4... , but they seem not included in the notebook. I wonder where I can find them?
![image](https://github.com/phbradley/conga/assets/78600759/37b4df0d-2d69-4f42-87c3-546dcc004adc)

Thanks for developing such a fantastic tool.

**Comment by phbradley** [comment]
Hi there,
Thanks for your interest and kind words! Sorry that wasn't clear. Those refer to notes in this paper (attached):

Schattgen, S. A., Hazelton, W. D., Thomas, P. G., & Bradley, P. (2022). Multimodal T Cell Analysis with CoNGA. Methods in Molecular Biology , 2574, 367–388.

[Schattgen et al. 2022 - Multimodal T Cell Analysis with CoNGA.pdf](https://github.com/user-attachments/files/16120173/Schattgen.et.al.2022.-.Multimodal.T.Cell.Analysis.with.CoNGA.pdf)
